apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: n6zmq5sb4-go
  janus-idp.io/tekton: n6zmq5sb4-go
  backstage.io/kubernetes-id: n6zmq5sb4-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: n6zmq5sb4-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
